<a href="https://colab.research.google.com/github/Sahuva-S/Assessment2_Sahuva_S/blob/main/Assessment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SECTION A

In [1]:
import numpy as np
import pandas as pd

Q1

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data type: int64

Q2.

In [5]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])

#q2.1
add =  arr + 5
print("Added result:",add)

#q2.2
mul = arr * 2
print("Elements which are multiply by 2:",mul)

Added result: [10 15 20 25 30]
Elements which are multiply by 2: [10 20 30 40 50]

Q3

In [6]:
import numpy as np

arr = np.array([12, 15, 18, 20, 25, 30])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard Deviation:", np.std(arr))

Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.027713773341708

Q4

In [9]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])
res = arr[arr > 40]
print("Array greater than 40:",res)

Array greater than 40: [45 50 65 70]

Q5

In [13]:
df = pd.DataFrame({
    'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],
    'Age': [21, 22, 20, 23],
    'Score': [85, 72, 91, 68]
})
print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

Q6

In [14]:
#q6.1
print(df[["Name", "Score"]])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

In [15]:
#q6.2
print(df[df["Name"] == "Meera"])

    Name  Age  Score
2  Meera   20     91

Q7

In [16]:
result = df[df["Score"] > 75]

print(result)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

Q8

In [18]:
print("Shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

print("\nStatistical summary:")
print(df.describe())

Shape:
(4, 3)

Column names:
Index(['Name', 'Age', 'Score'], dtype='object')

Data types:
Name     object
Age       int64
Score     int64
dtype: object

Statistical summary:
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

Q9

In [19]:
result=df.sort_values("Score", ascending=False)
print(result)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

Q10

In [21]:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})
print(df)

  Name   Age  Score
0    A  21.0   80.0
1    B   NaN   75.0
2    C  23.0    NaN
3    D  22.0   90.0

In [23]:
#q10.1
print(df.isnull())

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [24]:
#q10.2
print(df.isnull().sum())

Name     0
Age      1
Score    1
dtype: int64

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

In [31]:
#q10.3
df["Score"] = df["Score"].fillna(df["Score"].mean())
print(df)

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

SECTION B

Q11

In [33]:
df = pd.read_csv("student_performance.csv")
print(df)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

[80 rows x 11 columns]

In [38]:
#q11.1
print("First 5 records:")
df.head()

First 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

In [40]:
#q11.2
print("last 5 records:")
df.tail()

last 5 records:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [44]:
#q11.3
print("Number of rows and columns:")
df.shape

Number of rows and columns:

(80, 11)

In [46]:
#q11.4
print("Column names:")
df.columns

Column names:

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [47]:
#q11.5
print("Data types:")
df.dtypes

Data types:

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [50]:
#q11.6
print("Statistical summary of the numerical columns:")
df.describe()

Statistical summary of the numerical columns:

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

Q12

In [55]:
#q12.1
res1 = df[df["Final_Score"] > 75]
print(res1)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

In [56]:
#q12.2
res2 = df[df["Attendance"] < 75]
print(res2)

   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

In [57]:
df["Department"] = df["Department"].str.strip().str.title()

In [58]:
#q12.3
res3 = df[
    (df["Department"] == "Data Science") &
    (df["Final_Score"] > 80)
]

print(res3)

   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

In [59]:
#q12.4
res4 = df.sort_values("Final_Score", ascending=False)
print(res4)

   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

Q13

In [62]:
df["Average_Technical_Score"] = df[
    ["Python_Score", "SQL_Score", "Pandas_Score", "NumPy_Score"]
].mean(axis=1)

df["Performance"] = np.select(
    [
        df["Average_Technical_Score"] >= 90,
        df["Average_Technical_Score"] >= 75,
        df["Average_Technical_Score"] >= 60
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Needs Improvement"
)
score_columns = [
    "Python_Score",
    "SQL_Score",
    "Pandas_Score",
    "NumPy_Score"
]

for col in score_columns:
    df[col] = df[col].fillna(df[col].mean())

print(df)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score        Performance
0                    83.575               Good
1                    65.200            Average
2                    73.400            Average
3                    54.475  Needs Improvement
4                    83.275               Good
..                      ...                ...
75                   47.775  Needs Improvement
76                   46.525  Needs Improvement
77                   80.250               Good
78                   61.350            Average
79                   77.075               Good

[80 rows x 13 columns]

Q14

In [63]:
result = df.groupby("Department").agg(
    Number_of_Students=("Student_ID", "count"),
    Average_Final_Score=("Final_Score", "mean"),
    Maximum_Final_Score=("Final_Score", "max"),
    Minimum_Final_Score=("Final_Score", "min")
)

result = result.sort_values("Average_Final_Score",ascending=False)
print(result)

                  Number_of_Students  Average_Final_Score  \
Department
Electronics                       13            72.846154
Computer Science                  30            70.653333
Data Science                      29            70.559259
Commerce                           8            67.825000

                  Maximum_Final_Score  Minimum_Final_Score
Department
Electronics                      86.9                 51.2
Computer Science                 96.0                 40.6
Data Science                     97.0                 43.5
Commerce                         83.7                 54.6

Q15

In [64]:
#q15.1
final_scores = df["Final_Score"].to_numpy()

In [65]:
#q15.2
final_scores = df["Final_Score"].dropna().to_numpy()

In [67]:
#q15.3
print("Mean:", np.mean(final_scores))

Mean: 70.69615384615383

In [66]:
#q15.4
print("Median:", np.median(final_scores))

Median: 70.95

In [68]:
#q15.5
print("Standard Deviation:", np.std(final_scores))

Standard Deviation: 13.96349124578818

In [69]:
#q15.6
print("25th Percentile:", np.percentile(final_scores, 25))

25th Percentile: 60.449999999999996

In [70]:
#q15.7
print("75th Percentile:", np.percentile(final_scores, 75))

75th Percentile: 82.275

In [72]:
#q15.8
overall_mean = df["Final_Score"].mean()
above_mean = df[df["Final_Score"] > overall_mean]
print(above_mean)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai  Female  Computer Science  19.0        67.3
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
20    STU1021      Arun Varma  Female          Commerce  25.0        79.5
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
46    STU1047       Gokul Das    Male      Data Science  21.0         NaN
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
52    STU1053      Maya Varma    Male  Computer Science  22.0        84.6
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
60    STU1061  Fathima Sharma    Male  Computer Science  24.0        79.6
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
66    STU1067    Rahul Thomas    Male      Data Science   NaN        99.3
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
72    STU1073   Swathi Joseph    Male      Data Science  22.0        78.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
74    STU1075      Gokul Nair  Female      Data Science  23.0        87.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0      89.400000       86.3     81.900000    76.700000         82.7
4      90.100000       82.9     72.400000    87.700000         81.9
6      81.700000       82.2     81.500000    64.200000         77.0
7      72.100000       80.4     72.900000    73.500000         79.2
8      94.800000       86.0     87.700000   100.000000         83.0
9      79.600000       85.0     74.100000    80.500000         73.8
10    100.000000       93.2    100.000000    89.300000         91.9
11     80.400000       78.0     88.900000    77.100000         86.9
16     80.800000       99.4     77.200000   100.000000         91.1
17     62.600000       81.6     79.600000    75.500000         75.1
20     72.821795       67.6     74.300000    75.300000         73.2
23     87.700000       71.0     88.500000    74.800000         83.7
24     87.500000       67.1     84.500000    96.100000         77.3
27     70.300000       82.0     64.400000    72.800000         77.1
30     86.900000       64.3    100.000000    89.200000         85.5
33     94.400000       81.6     71.300000    81.500000         84.3
35     95.300000       93.4    100.000000    62.500000         84.2
37     87.800000       78.3     85.500000    82.700000         82.4
39     68.900000       79.8     66.100000    66.400000         78.5
40     94.300000       91.0     73.100000    91.200000         94.5
41     71.200000       76.1     70.800000    68.574359         77.9
43     68.000000       67.3     83.600000    76.700000         77.3
46     69.500000       59.3     75.200000    75.200000         74.8
47     80.600000       67.0     71.200000    80.200000         77.3
48     88.900000       95.0     70.365385    94.500000         97.0
51     80.400000       85.3     96.700000    83.500000         79.3
52     71.900000       73.4     70.000000    67.200000         71.0
55     87.000000       95.1     88.400000    75.700000         93.3
56     72.100000       66.9     61.800000    72.300000         75.2
57     93.100000       78.8     91.600000    83.800000         92.3
58     99.700000       77.1     68.900000    89.700000         84.9
59    100.000000       85.0     87.400000    57.400000         87.9
60     80.800000       63.1     71.100000    67.900000         70.8
61    100.000000      100.0     89.400000    91.400000         96.0
64     96.500000       69.3     86.700000    80.700000         83.5
66     72.821795       56.2     69.000000    81.500000         70.7
67     83.400000       79.6     89.300000    83.600000         83.7
72     76.400000       77.5     73.600000    65.600000         73.5
73     95.300000       67.7     92.400000    81.400000         83.4
74     85.400000       80.0     65.200000    70.400000         70.9
77     70.400000       75.7     98.200000    76.700000         75.2
79     80.500000       94.3     58.600000    74.900000         78.6

    Average_Technical_Score Performance
0                    83.575        Good
4                    83.275        Good
6                    77.400        Good
7                    74.725     Average
8                    92.125   Excellent
9                    79.800        Good
10                   95.625   Excellent
11                   81.100        Good
16                   89.350        Good
17                   74.825     Average
20                   72.400     Average
23                   80.500        Good
24                   83.800        Good
27                   72.375     Average
30                   85.100        Good
33                   82.200        Good
35                   87.800        Good
37                   83.575        Good
39                   70.300     Average
40                   87.400        Good
41                   72.700     Average
43                   73.900     Average
46                   69.800     Average
47                   74.750     Average
48                   92.800   Excellent
51                   86.475        Good
52                   70.625     Average
55                   86.550        Good
56                   68.275     Average
57                   86.825        Good
58                   83.850        Good
59                   82.450        Good
60                   70.725     Average
61                   95.200   Excellent
64                   83.300        Good
66                   68.900     Average
67                   83.975        Good
72                   73.275     Average
73                   84.200        Good
74                   75.250        Good
77                   80.250        Good
79                   77.075        Good

SECTION C

In [73]:
#16.A[MISSING VALUES]

print(df.isnull().sum())

Student_ID                 0
Name                       0
Gender                     0
Department                 0
Age                        3
Attendance                 3
Python_Score               0
SQL_Score                  0
Pandas_Score               0
NumPy_Score                0
Final_Score                2
Average_Technical_Score    0
Performance                0
dtype: int64

In [75]:
#16.A[HANDLING MISSING NUMERICAL VALUES]
numeric_columns = [
    "Age","Attendance", "Python_Score", "SQL_Score","Pandas_Score","NumPy_Score","Final_Score"
]
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].mean())

16B

In [76]:
#16.b[CREATE A COLUMN FOR AVERAGE SCORE]
df["Average_Score"] = df[
    ["Python_Score", "SQL_Score", "Pandas_Score", "NumPy_Score"]
].mean(axis=1)

In [78]:
#16.B[CREATE A COLUMN PASS STATUS]
df["Pass_Status"] = np.where(
    df["Average_Score"] >= 50,
    "Pass",
    "Fail"
)

In [79]:
print(df)

   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score  Average_Technical_Score        Performance  Average_Score  \
0          82.7                   83.575               Good         83.575
1          60.3                   65.200            Average         65.200
2          67.1                   73.400            Average         73.400
3          57.2                   54.475  Needs Improvement         54.475
4          81.9                   83.275               Good         83.275
..          ...                      ...                ...            ...
75         47.2                   47.775  Needs Improvement         47.775
76         43.5                   46.525  Needs Improvement         46.525
77         75.2                   80.250               Good         80.250
78         63.4                   61.350            Average         61.350
79         78.6                   77.075               Good         77.075

   Pass_Status
0         Pass
1         Pass
2         Pass
3         Pass
4         Pass
..         ...
75        Fail
76        Fail
77        Pass
78        Pass
79        Pass

[80 rows x 15 columns]

16 C

In [80]:
#16.C.1
top5 = df.nlargest(5, "Average_Score")
print(
    top5[
        ["Student_ID", "Name", "Department", "Average_Score"]
    ]
)

   Student_ID          Name        Department  Average_Score
10    STU1011      Diya Das      Data Science         95.625
61    STU1062  Kiran Pillai  Computer Science         95.200
8     STU1009    Diya Menon      Data Science         92.125
16    STU1017  Rahul Thomas      Data Science         89.350
35    STU1036    Maya Menon       Electronics         87.800

In [81]:
#16.C.2
department_average = df.groupby("Department")["Average_Score"].mean()
print(department_average)
highest_department = department_average.idxmax()
print("Highest:", highest_department)

Department
Commerce            68.806931
Computer Science    69.959573
Data Science        70.071143
Electronics         74.063462
Name: Average_Score, dtype: float64
Highest: Electronics

In [82]:
#16.c.3
average_attendance = df.groupby(
    "Department"
)["Attendance"].mean()

print(average_attendance)

Department
Commerce            77.437500
Computer Science    83.079091
Data Science        81.877429
Electronics         80.576923
Name: Attendance, dtype: float64

In [83]:
#16.c.4
print(df["Pass_Status"].value_counts())

Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64

16D

In [85]:
summary = df.groupby("Department").agg(
    Total_Students=("Student_ID", "count"),
    Average_Score=("Average_Score", "mean"),
    Average_Attendance=("Attendance", "mean"),
    Pass_Count=("Pass_Status", lambda x: (x == "Pass").sum()),
    Fail_Count=("Pass_Status", lambda x: (x == "Fail").sum())
).reset_index()

print(summary)

         Department  Total_Students  Average_Score  Average_Attendance  \
0          Commerce               8      68.806931           77.437500
1  Computer Science              30      69.959573           83.079091
2      Data Science              29      70.071143           81.877429
3       Electronics              13      74.063462           80.576923

   Pass_Count  Fail_Count
0           8           0
1          25           5
2          26           3
3          13           0

Q17

In [86]:
#17.1
sales = pd.read_csv("sales.csv")
print(sales.head())

  Order_ID  Order_Date       Product     Category Region  Sales  Quantity  \
0  ORD5001  2026-06-10  Office Chair    Furniture   East  142.1       1.0
1  ORD5002  2026-04-25       USB Hub  Accessories  North  51.52       2.0
2  ORD5003  2026-03-07       Monitor    Computers   West  648.0       4.0
3  ORD5004  2026-03-19  Office Chair    Furniture  North  290.0       2.0
4  ORD5005  2026-01-25        Tablet    Computers  North  304.0       1.0

  Discount  Profit
0     0.02   12.78
1     0.08    4.57
2      0.1   86.32
3      0.0   47.77
4     0.05   23.43

In [87]:
#17.2
sales["Order_Date"] = pd.to_datetime(
    sales["Order_Date"],
    format="mixed"
)

In [88]:
for col in ["Product", "Category", "Region"]:
    sales[col] = sales[col].str.strip()

In [89]:
for col in ["Sales", "Quantity", "Discount", "Profit"]:
    sales[col] = (
        sales[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("%", "", regex=False)
    )

    sales[col] = pd.to_numeric(
        sales[col],
        errors="coerce"
    )

In [90]:
for col in ["Sales", "Quantity", "Discount", "Profit"]:
    sales[col] = sales[col].fillna(sales[col].mean())
for col in ["Region", "Product", "Category"]:
    sales[col] = sales[col].fillna(sales[col].mode()[0])

Q17B

In [91]:
#q17.b.1
total_sales = sales["Sales"].sum()
print("Total Sales:", total_sales)

Total Sales: 94400.44

In [92]:
#q17.b.2
total_profit = sales["Profit"].sum()
print("Total Profit:", total_profit)

Total Profit: 15245.16536312849

In [93]:
#q17.b.3
average_sales = sales["Sales"].mean()
print("Average Sales:", average_sales)

Average Sales: 524.4468888888889

In [94]:
#q17.b.4
top_products = (
    sales.groupby("Product")["Sales"].sum()
    .sort_values(ascending=False)
    .head(5)
)

print(top_products)

Product
Laptop        33995.0
Printer       13719.3
Tablet        10291.2
Monitor        9508.9
Headphones     5999.5
Name: Sales, dtype: float64

In [96]:
#q17.5
highest_sales = (
    sales.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(highest_sales)

Region
West     37314.18
South    31672.75
North    18748.98
East      6158.53
south      506.00
Name: Sales, dtype: float64

Q17 C

In [ ]:
category_summary = sales.groupby("Category").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Average_Discount=("Discount", "mean")
)

category_summary = category_summary.sort_values(
    "Total_Sales",
    ascending=False
)

print(category_summary)

Q18

In [101]:
employee = pd.read_csv("employee.csv")
print(df)

   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score  Average_Technical_Score        Performance  Average_Score  \
0          82.7                   83.575               Good         83.575
1          60.3                   65.200            Average         65.200
2          67.1                   73.400            Average         73.400
3          57.2                   54.475  Needs Improvement         54.475
4          81.9                   83.275               Good         83.275
..          ...                      ...                ...            ...
75         47.2                   47.775  Needs Improvement         47.775
76         43.5                   46.525  Needs Improvement         46.525
77         75.2                   80.250               Good         80.250
78         63.4                   61.350            Average         61.350
79         78.6                   77.075               Good         77.075

   Pass_Status
0         Pass
1         Pass
2         Pass
3         Pass
4         Pass
..         ...
75        Fail
76        Fail
77        Pass
78        Pass
79        Pass

[80 rows x 15 columns]